HEADER:
  label: "About me"

PRESENTATION:
  description:

    Experienced Security Professional specializing in Cloud & Application Security, with expertise in architecting access control policies, integrating PAM solutions, & security frameworks. Proficient in conducting vulnerability assessments & advanced reporting, with a strong focus on enhancing security postures through threat mitigation & ASM monitoring.

DOING:
  enabled: true
  label: "What I'm doing"
  items:
    - title: "Security Researcher @Security Brigade"
      icon: "config/assets/icons/mobile.svg"
      description: "Led the deployment of ShadowMap for Attack Surface Management, enhancing external threat visibility and reducing incident response times by 35%. -- Project I
      Developed iInsights VRMS from scratch, aligning with NIST and OWASP standards, for comprehensive vulnerability management, detection, and actionable remediation recommendations. – Project II"
    - title: "Advisory Board Member and Ambassador @APISec University"
      icon: "config/assets/icons/code.svg"
      description: "Contributed to OffSec research, curriculum development & education through webinars & OWASP-based best practices."
    - title: "Cloud Solutions Architect"
      icon: "config/assets/icons/compass.svg"
      description: "Migrated VMware ESXi to Hyper-V on AWS-S3 buckets and configured a DR policy to sync data to HP C7000 blades."
    - title: "Cloud Security Engineer"
      icon: "config/assets/icons/laptop-code.svg"
      description: "Deployed ZTNA for secure remote access, minimizing the attack surface and optimizing FWaaS policies for compliance."
    - title: "IAM Solutions Architect"
      icon: "config/assets/icons/compass.svg"
      description: "Streamlined identity management with SailPoint, Thycotic PAM, & AD, ensuring compliance and data integrity."
    - title: "Vulnerability Management Specialist"
      icon: "config/assets/icons/compass.svg"
      description: "Executed InsightVM scans, deploying Local Engine for targeted detection & enhanced endpoint detection." 
    - title: "OT Security Consultant"
      icon:  "config/assets/icons/compass.svg"
      description: "– Led global ARMIS deployment, assessed security gaps with client data, and drove seamless revenue generation."
    - title: "Security Risk and Compliance Architect"
      icon: "config/assets/icons/compass.svg"
      descripition: "– Enforced policies via ServiceNow, automating risk scoring, compliance, & governance with real-time analytics."
    - title: "" 
SKILLS:
  enabled: true
  label: "Soft Skills"
  items:
    - title: "Fast Learner"
      icon: "config/assets/icons/bolt.svg"
      description: "I have the ability to quickly acquire new knowledge and adapt to changing technological environments."
    - title: "Teamwork"
      icon: "config/assets/icons/user.svg"
      description: "I collaborate effectively in multidisciplinary projects and communicate clearly with team members."
    - title: "Problem Solving"
      icon: "config/assets/icons/gear.svg"
      description: "I am creative and efficient in identifying and solving technical problems."
    - title: "Effective Communication"
      icon: "config/assets/icons/comment.svg"
      description: "I have the skill to convey ideas clearly and concisely, both technically and non-technically."

TECHNOLOGIES:
  enabled: true
  label: "Tech Experience"
  items:
    - title: "Python"
      icon: "config/assets/icons/python.svg"
    - title: "Flutter"
      icon: "config/assets/icons/flutter.svg"
    - title: "Git"
      icon: "config/assets/icons/git.svg"
    - title: "Cloud Security"
      icon: "config/assets/icons/figma.svg"
    - title: "Vulnerability Management"
      icon: "config/assets/icons/firebase.svg"
    - title: "Exploit Development"
      icon: "config/assets/icons/pandas.svg"
    - title: "Kali Linux"
      icon: "config/assets/icons/mongodb.svg"
    - title: "Offensive Security - Red Teaming and Penetration Testing"
      icon: "config/assets/icons/dart.svg"
    - title: "ML"
      icon: "config/assets/icons/html.svg"
    - title: "AI"
      icon: "config/assets/icons/ai.svg"
    - title: "NLP"
      icon: "config/assets/icons/jupyter.svg"
    - title: "LLM"
      icon: "config/assets/icons/linux.svg"
