HEADER:
  label: "Contact"

LOCATION:
  embed: "https://forms.gle/xbB9FifEWFLaQumz8"

FORM:
  label: "Contact Form"
  fields:
    - name: "Full name"
    - email: "Email address"
    - message: "Your message"
    - submit: "Send message"
