# We are using the ionicons icon set https://ionic.io/ionicons
# For example, to add a linkedin icon:
# <ion-icon name="logo-linkedin"></ion-icon>
# - icon: "logo-linkedin"

HEADER:
  label: "Show Contacts"

USER:
  role: "Security Researcher"
  name: "Shashank Mishra"
  username: "the_dark_knight  --  silent_yet_string" # <-- This needs to be the same as your GitHub username
  avatar: "config/assets/avatars/my-avatar.png"

INFO:
  - label: "Email"
    value: "reachtheshashankmishra@gmail.com"
    icon: "mail-outline"
  - label: "Phone"
    value: "+91 (799) 354-9827"
    icon: "phone-portrait-outline"
  - label: "Birthday"
    value: "October 16, 2000"
    icon: "calendar-outline"
  - label: "Location"
    value: "Mumbai, Maharashtra, India"
    icon: "location-outline"

SOCIAL:
  - icon: "logo-facebook"
    url: "https://facebook.com/"
  - icon: "logo-twitter"
    url: "https://twitter.com/"
  - icon: "logo-instagram"
    url: "https://instagram.com/"
  - icon: "logo-linkedin"
    url: "https://www.linkedin.com/in/shashankmishra24/"
  - icon: "logo-github"
    url: "https://github.com/Shajohn16"
  - icon: "logo-dribbble"
    url: "https://www.reddit.com/user/No_Tradition2318/"
