HEADER:
  label: "Portfolio"

PROJECTS:
  - title: "Smart Helmet with Alcohol Sensor"
    category: "IoT Devices with Electronics and Security"
    description: "Developed a tamper-proof helmet with Arduino UNO, MQ3 sensors, and IoT for real-time safety compliance. Ensured data security using secure APIs, encryption, RBAC, and OWASP standards. Designed hardware with GSM, RF modules, and relays for ignition interlock and emergency alerts."
    image: "https://i.imgur.com/ANDVQ4o.png"
    url: "https://github.com/ivansaul/flutter_cinemapedia_app#screenshots"