HEADER:
  label: "Resume"

EDUCATION:
  enabled: true
  label: "Education"
  items:
    - period: "2019 — 2023"
      institution: "Veer Madho Singh Bhandari Uttarrakhand Technical University"
      description: "Graduated with honors, focusing on AI & ML and IoT. Participated in multiple student exhibitions, honing skills in drawing, painting, and graphic design. Was the College president"
    - period: "2023 — 2024"
      institution: "IIM Shillong"
      description: "Post Graduate Diploma Certification in Management Consultancy, was the Senior Content Writer in the editorail board."
    - period: "2024 — 2025"
      institution: "IIT Ropar"
      description: "Post Graduate Diploma in Artificial Intelligence and Machine Learning with a focus on Natural Language Processing and Large Language Models."
    - period: "2023 — 2024"
      institution: "IMI BBSR"
      description: "Post Graduate Diploma Certification in Microsoft Excel for Business Administration."
    - period: "2023-2024"
      institution: "IMI BBSR"
      descripition: "Microsoft Power BI for Investment Banking"
    - period: "2023-2024"
      institution: "IIT Kanpur"
      descripition: "Blue Teaming ~ Defensive Security - CSCUv2"
    - period: "2023-2024"
      institution: "IIT Kanpur"
      descripition: "Purple Teaming ~ Defensive Security - CHFIv10"
    - period: "2023-2024"
      institution: "IIT Kanpur"
      descripition: "Red Teaming ~ Offensive Security - CEHv12"
    - period: "2024-2025"
      institution: "BIA Mumbai"
      descripition: "Advanced Offensive Security - Red Teaming and Penetration Testing"
    - period: "2023-2024"
      institution: "IIT Kanpur"
      descripition: "Blue Teaming ~ Defensive Security - CSCUv2"

EXPERIENCE:
  enabled: true
  label: "Experience"
  items:
    - period: "2024 — Present"
      position: "Security Researcher @Security Brigade"
      description: "Led the deployment of ShadowMap for Attack Surface Management, enhancing external threat visibility and reducing incident response times by 35%. –- Project I"
      descripition: "Developed iInsights VRMS from scratch, aligning with NIST and OWASP standards, for comprehensive vulnerability management, detection, and actionable remediation recommendations. -– Project II"
    - period: "2024 - Present"
      position: "Advisory Board Member and Ambassador"
      description: "– Contributed to OffSec research, curriculum development & education through webinars & OWASP-based best practices."
    - period: " 2024 -  2024"
      position: "Cloud Solutions Architect @Freelance"
      description: "– Migrated VMware ESXi to Hyper-V on AWS-S3 buckets and configured a DR policy to sync data to HP C7000 blades."
    - position: "Cloud Security Engineer @Freelance"
      period: " 2024 -  2024"
      descripition: "– Deployed ZTNA for secure remote access, minimizing the attack surface and optimizing FWaaS policies for compliance."
    - position: "IAM Solutions Architect @Freelance"
      period: " 2023 -  2024"
      descripition: "– Streamlined identity management with SailPoint, Thycotic PAM, & AD, ensuring compliance and data integrity."
    - position: "Vulnerability Management Specialist @Freelance"
      period: " 2023 -  2023"
      descripition: "– Executed InsightVM scans, deploying Local Engine for targeted detection & enhanced endpoint detection."
    - position: "OT Security Consultant @Freelance"
      period: " 2023 - 2023"
      descripition: "– Led global ARMIS deployment, assessed security gaps with client data, and drove seamless revenue generation."
    - position: "Security Risk and Compliance Architect @Freelance"
      period: "2023 - 2023"
      descripition: "– Enforced policies via ServiceNow, automating risk scoring, compliance, & governance with real-time analytics."
    - position: "Security Intern @Hacktify Cyber Security"
      period: "2024 - 2024"
      descripition : "– Researched on Cyber Crime & delivered security awareness programs to maintain policies & for threat hunting."
    - position: "SOC Intern  @Chaitanya Cyber Strix Technologies Pvt. Ltd."
      period: "2023 - 2024"
      descripition : "– Monitored security events with SIEM, applied threat intelligence, & supported incident response and compliance."
    - position: "Project Engineer Intern – Dehradun Smart City Limited (DSCL)"
      period: "2022 - 2022"
      descripition : "– Led a 17-member team to integrate IoT with electrical systems, optimizing resources & ensuring safety compliance."
    
LANGUAGES:
  enabled: true
  display_progress_bars: true
  display_percentage_values: true
  label: "Languages"
  items:
    - language: "English"
      proficiency: "90%"
    - language: "Hindi"
      proficiency: "95%"

SKILLS:
  enabled: true
  display_progress_bars: true
  display_percentage_values: true
  label: "My Skills"
  items:
    - skill: "Penetration Testing"
      proficiency: "80%"
    - skill: "Cloud Security"
      proficiency: "70%"
    - skill: "Kali linux"
      proficiency: "80%"
    - skill: "Pyhton"
      proficiency: "60%"
    - skill: "Vulnerability Management"
      proficiency: "70%"